import {
  BarChart3,
  Bot,
  Globe2,
  LineChart,
  Megaphone,
  Search,
  ShieldCheck,
  ShoppingBag,
} from "lucide-react";

export const useCases = [
  {
    id: "web-scraping",
    slug: "web-scraping",
    title: "Web Scraping",
    shortTitle: "Public Web Data",
    description: "Collect public web data reliably for research, analytics and monitoring.",
    bestProduct: "Residential Proxies",
    icon: Bot,
    points: ["Public data collection", "Rotating sessions", "Country targeting", "Usage visibility"],
  },
  {
    id: "seo-monitoring",
    slug: "seo-monitoring",
    title: "SEO Monitoring",
    shortTitle: "SEO Monitoring",
    description: "Run rank tracking, SERP checks and geo-specific search visibility workflows.",
    bestProduct: "Residential Proxies",
    icon: Search,
    points: ["Regional SERP checks", "Rank reporting", "Search visibility QA", "SERP API coming soon"],
  },
  {
    id: "ecommerce-monitoring",
    slug: "ecommerce-monitoring",
    title: "Ecommerce Monitoring",
    shortTitle: "Ecommerce",
    description: "Monitor prices, availability and product catalogs across regions.",
    bestProduct: "Datacenter Proxies",
    icon: ShoppingBag,
    points: ["Price monitoring", "Stock checks", "Catalog research", "Regional insights"],
  },
  {
    id: "ad-verification",
    slug: "ad-verification",
    title: "Ad Verification",
    shortTitle: "Ad Verification",
    description: "Check ad placement, regional campaign visibility and brand safety.",
    bestProduct: "Mobile Proxies",
    icon: Megaphone,
    points: ["Geo-specific campaign QA", "Placement checks", "Mobile network context", "Brand safety"],
  },
  {
    id: "market-research",
    slug: "market-research",
    title: "Market Research",
    shortTitle: "Market Research",
    description: "Gather public market signals, trends and regional competitive intelligence.",
    bestProduct: "Residential Proxies",
    icon: LineChart,
    points: ["Regional insights", "Trend monitoring", "Public data research", "Competitive intelligence"],
  },
  {
    id: "social-media-management",
    slug: "social-media-management",
    title: "Social Media Management",
    shortTitle: "Social Management",
    description: "Support legitimate team workflows with stable network identities and clear compliance controls.",
    bestProduct: "Static ISP Proxies",
    icon: ShieldCheck,
    points: ["Team workflows", "Stable sessions", "IP whitelist controls", "Compliance-first positioning"],
  },
  {
    id: "geo-testing",
    slug: "geo-testing",
    title: "Geo-specific Testing",
    shortTitle: "Geo Testing",
    description: "Test localized content, pricing and application behavior from target regions.",
    bestProduct: "Datacenter Proxies",
    icon: Globe2,
    points: ["Localization QA", "Country selection", "City targeting placeholders", "Developer workflows"],
  },
  {
    id: "automation",
    slug: "automation",
    title: "Automation Workflows",
    shortTitle: "Automation",
    description: "Run business automation and monitoring tasks with predictable proxy configuration.",
    bestProduct: "Datacenter Proxies",
    icon: BarChart3,
    points: ["Predictable endpoints", "Protocol choice", "Traffic controls", "Dashboard management"],
  },
];

export function getUseCaseBySlug(slug: string) {
  return useCases.find((useCase) => useCase.slug === slug);
}
